/* Geprüfte Fachquellen für die Lernmodule. Module nennen Quellen nur über
   diese Schlüssel – so steht nie eine erfundene Literaturangabe in der App. */
window.LERN_QUELLEN = {
  /* Klassifikation & Leitlinien */
  dsm5tr: 'American Psychiatric Association (2022). Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition, Text Revision (DSM-5-TR). Washington, DC: APA.',
  icd11: 'World Health Organization (2019). International Classification of Diseases, 11th Revision (ICD-11). Genf: WHO.',
  niceNG87: 'NICE (2018). Attention deficit hyperactivity disorder: diagnosis and management (NG87). London: National Institute for Health and Care Excellence.',
  niceCG158: 'NICE (2013). Antisocial behaviour and conduct disorders in children and young people: recognition and management (CG158). London: NICE.',
  niceCG170: 'NICE (2013). Autism spectrum disorder in under 19s: support and management (CG170). London: NICE.',
  niceCG159: 'NICE (2013). Social anxiety disorder: recognition, assessment and treatment (CG159). London: NICE.',
  niceNG134: 'NICE (2019). Depression in children and young people: identification and management (NG134). London: NICE.',
  niceNG116: 'NICE (2018). Post-traumatic stress disorder (NG116). London: NICE.',
  niceNG225: 'NICE (2022). Self-harm: assessment, management and preventing recurrence (NG225). London: NICE.',
  niceNG69: 'NICE (2017). Eating disorders: recognition and treatment (NG69). London: NICE.',
  niceNG26: 'NICE (2015). Children’s attachment: attachment in children and young people who are adopted from care, in care or at high risk of going into care (NG26). London: NICE.',
  awmfAdhs2018: 'AWMF (2018). S3-Leitlinie „Aufmerksamkeitsdefizit-/Hyperaktivitätsstörung (ADHS) im Kindes-, Jugend- und Erwachsenenalter“ (AWMF-Registernummer 028-045).',
  aeraStandards2014: 'AERA, APA & NCME (2014). Standards for Educational and Psychological Testing. Washington, DC: American Educational Research Association.',
  whoMaltreatment2006: 'World Health Organization & ISPCAN (2006). Preventing child maltreatment: a guide to taking action and generating evidence. Genf: WHO.',

  /* Lehrbücher */
  petermann2013: 'Petermann, F. (Hrsg.) (2013). Lehrbuch der Klinischen Kinderpsychologie (7. Aufl.). Göttingen: Hogrefe.',
  fegert2012: 'Fegert, J. M., Eggers, C. & Resch, F. (Hrsg.) (2012). Psychiatrie und Psychotherapie des Kindes- und Jugendalters (2. Aufl.). Berlin: Springer.',
  schneiderMargraf2019: 'Schneider, S. & Margraf, J. (Hrsg.) (2019). Lehrbuch der Verhaltenstherapie, Band 3: Psychologische Therapie bei Indikationen im Kindes- und Jugendalter (2. Aufl.). Berlin: Springer.',
  rutter2015: 'Thapar, A., Pine, D. S., Leckman, J. F., Scott, S., Snowling, M. J. & Taylor, E. (Eds.) (2015). Rutter’s Child and Adolescent Psychiatry (6th ed.). Chichester: Wiley-Blackwell.',
  schneiderLindenberger2018: 'Schneider, W. & Lindenberger, U. (Hrsg.) (2018). Entwicklungspsychologie (8. Aufl.). Weinheim: Beltz.',
  barkley2015: 'Barkley, R. A. (2015). Attention-Deficit Hyperactivity Disorder: A Handbook for Diagnosis and Treatment (4th ed.). New York: Guilford.',
  gerlach2016: 'Gerlach, M., Mehler-Wex, C., Walitza, S., Warnke, A. & Wewetzer, C. (Hrsg.) (2016). Neuro-Psychopharmaka im Kindes- und Jugendalter (3. Aufl.). Berlin: Springer.',
  grossmann2012: 'Grossmann, K. & Grossmann, K. E. (2012). Bindungen – das Gefüge psychischer Sicherheit (5. Aufl.). Stuttgart: Klett-Cotta.',
  wechsler2014: 'Wechsler, D. (2014). WISC-V: Technical and Interpretive Manual. Bloomington, MN: Pearson.',

  /* Übersichtsarbeiten */
  faraone2021: 'Faraone, S. V. et al. (2021). The World Federation of ADHD International Consensus Statement: 208 evidence-based conclusions about the disorder. Neuroscience & Biobehavioral Reviews, 128, 789–818.',
  cortese2018: 'Cortese, S. et al. (2018). Comparative efficacy and tolerability of medications for attention-deficit hyperactivity disorder in children, adolescents, and adults: a systematic review and network meta-analysis. The Lancet Psychiatry, 5(9), 727–738.',
  frick2014: 'Frick, P. J., Ray, J. V., Thornton, L. C. & Kahn, R. E. (2014). Can callous-unemotional traits enhance the understanding, diagnosis, and treatment of serious conduct problems in children and adolescents? A comprehensive review. Psychological Bulletin, 140(1), 1–57.',
  lord2018: 'Lord, C., Elsabbagh, M., Baird, G. & Veenstra-Vanderweele, J. (2018). Autism spectrum disorder. The Lancet, 392(10146), 508–520.',
  beesdo2009: 'Beesdo, K., Knappe, S. & Pine, D. S. (2009). Anxiety and anxiety disorders in children and adolescents: developmental issues and implications for DSM-V. Psychiatric Clinics of North America, 32(3), 483–524.',
  kearney2008: 'Kearney, C. A. (2008). School absenteeism and school refusal behavior in youth: A contemporary review. Clinical Psychology Review, 28(3), 451–471.',
  thapar2012: 'Thapar, A., Collishaw, S., Pine, D. S. & Thapar, A. K. (2012). Depression in adolescence. The Lancet, 379(9820), 1056–1067.',
  hawton2012: 'Hawton, K., Saunders, K. E. A. & O’Connor, R. C. (2012). Self-harm and suicide in adolescents. The Lancet, 379(9834), 2373–2382.',
  nock2010: 'Nock, M. K. (2010). Self-injury. Annual Review of Clinical Psychology, 6, 339–363.',
  treasure2020: 'Treasure, J., Duarte, T. A. & Schmidt, U. (2020). Eating disorders. The Lancet, 395(10227), 899–911.',
  zeanah2015: 'Zeanah, C. H. & Gleason, M. M. (2015). Annual research review: Attachment disorders in early childhood – clinical presentation, causes, correlates, and treatment. Journal of Child Psychology and Psychiatry, 56(3), 207–222.',
  sharpFonagy2015: 'Sharp, C. & Fonagy, P. (2015). Practitioner review: Borderline personality disorder in adolescence – recent conceptualization, intervention, and implications for clinical practice. Journal of Child Psychology and Psychiatry, 56(12), 1266–1288.',
  kaess2014: 'Kaess, M., Brunner, R. & Chanen, A. (2014). Borderline personality disorder in adolescence. Pediatrics, 134(4), 782–793.',
  /* Emotionale Instabilität, Selbstverletzung: DBT und MBT (für den Kompass im Hub) */
  niceCG78: 'NICE (2009). Borderline personality disorder: recognition and management (CG78). London: National Institute for Health and Care Excellence.',
  awmfBps2022: 'AWMF (2022). S3-Leitlinie Borderline-Persönlichkeitsstörung. Federführung: Deutsche Gesellschaft für Psychiatrie und Psychotherapie, Psychosomatik und Nervenheilkunde (DGPPN).',
  linehan1993: 'Linehan, M. M. (1993). Cognitive-Behavioral Treatment of Borderline Personality Disorder. New York: Guilford.',
  millerRathusLinehan2007: 'Miller, A. L., Rathus, J. H. & Linehan, M. M. (2007). Dialectical Behavior Therapy with Suicidal Adolescents. New York: Guilford.',
  rathusMiller2015: 'Rathus, J. H. & Miller, A. L. (2015). DBT Skills Manual for Adolescents. New York: Guilford.',
  rossouwFonagy2012: 'Rossouw, T. I. & Fonagy, P. (2012). Mentalization-based treatment for self-harm in adolescents: a randomized controlled trial. Journal of the American Academy of Child and Adolescent Psychiatry, 51(12), 1304–1313.',
  schulteKoerne2010: 'Schulte-Körne, G. (2010). The prevention, diagnosis, and treatment of dyslexia. Deutsches Ärzteblatt International, 107(41), 718–727.',
  butterworth2005: 'Butterworth, B. (2005). The development of arithmetical abilities. Journal of Child Psychology and Psychiatry, 46(1), 3–18.',
  bishop2017: 'Bishop, D. V. M. et al. (2017). Phase 2 of CATALISE: a multinational and multidisciplinary Delphi consensus study of problems with language development: Terminology. Journal of Child Psychology and Psychiatry, 58(10), 1068–1080.',
  steinhausenJuzi1996: 'Steinhausen, H.-C. & Juzi, C. (1996). Elective mutism: an analysis of 100 cases. Journal of the American Academy of Child and Adolescent Psychiatry, 35(5), 606–614.',
  leckmanCohen1999: 'Leckman, J. F. & Cohen, D. J. (1999). Tourette’s Syndrome – Tics, Obsessions, Compulsions. New York: Wiley.',
  marchMulle1998: 'March, J. S. & Mulle, K. (1998). OCD in Children and Adolescents: A Cognitive-Behavioral Treatment Manual. New York: Guilford.',
  casey2008: 'Casey, B. J., Jones, R. M. & Hare, T. A. (2008). The adolescent brain. Annals of the New York Academy of Sciences, 1124, 111–126.',
  vanDerKolk2005: 'van der Kolk, B. A. (2005). Developmental trauma disorder. Psychiatric Annals, 35(5), 401–408.',
  felitti1998: 'Felitti, V. J. et al. (1998). Relationship of childhood abuse and household dysfunction to many of the leading causes of death in adults: The Adverse Childhood Experiences (ACE) Study. American Journal of Preventive Medicine, 14(4), 245–258.',
  glaser2000: 'Glaser, D. (2000). Child abuse and neglect and the brain – a review. Journal of Child Psychology and Psychiatry, 41(1), 97–116.',
  mcewen1998: 'McEwen, B. S. (1998). Protective and damaging effects of stress mediators. New England Journal of Medicine, 338(3), 171–179.',
  rutter2012: 'Rutter, M. (2012). Resilience as a dynamic concept. Development and Psychopathology, 24(2), 335–344.',
  sroufe2005: 'Sroufe, L. A. (2005). Attachment and development: A prospective, longitudinal study from birth to adulthood. Attachment & Human Development, 7(4), 349–367.',
  maslach2016: 'Maslach, C. & Leiter, M. P. (2016). Understanding the burnout experience: recent research and its implications for psychiatry. World Psychiatry, 15(2), 103–111.',
  mccraeJohn1992: 'McCrae, R. R. & John, O. P. (1992). An introduction to the five-factor model and its applications. Journal of Personality, 60(2), 175–215.',
  engel1977: 'Engel, G. L. (1977). The need for a new medical model: A challenge for biomedicine. Science, 196(4286), 129–136.',
  gross1998: 'Gross, J. J. (1998). The emerging field of emotion regulation: An integrative review. Review of General Psychology, 2(3), 271–299.',
  durlak2011: 'Durlak, J. A., Weissberg, R. P., Dymnicki, A. B., Taylor, R. D. & Schellinger, K. B. (2011). The impact of enhancing students’ social and emotional learning: A meta-analysis of school-based universal interventions. Child Development, 82(1), 405–432.',
  stanleyBrown2012: 'Stanley, B. & Brown, G. K. (2012). Safety planning intervention: A brief intervention to mitigate suicide risk. Cognitive and Behavioral Practice, 19(2), 256–264.',

  /* Klassiker */
  bowlby1969: 'Bowlby, J. (1969). Attachment and Loss, Vol. 1: Attachment. New York: Basic Books.',
  ainsworth1978: 'Ainsworth, M. D. S., Blehar, M. C., Waters, E. & Wall, S. (1978). Patterns of Attachment. Hillsdale, NJ: Erlbaum.',
  mainSolomon1990: 'Main, M. & Solomon, J. (1990). Procedures for identifying infants as disorganized/disoriented during the Ainsworth Strange Situation. In M. T. Greenberg, D. Cicchetti & E. M. Cummings (Eds.), Attachment in the Preschool Years (pp. 121–160). Chicago: University of Chicago Press.',
  thomasChess1977: 'Thomas, A. & Chess, S. (1977). Temperament and Development. New York: Brunner/Mazel.',
  fonagy2002: 'Fonagy, P., Gergely, G., Jurist, E. L. & Target, M. (2002). Affect Regulation, Mentalization, and the Development of the Self. New York: Other Press.',
  young2003: 'Young, J. E., Klosko, J. S. & Weishaar, M. E. (2003). Schema Therapy: A Practitioner’s Guide. New York: Guilford.',
  vaillant1977: 'Vaillant, G. E. (1977). Adaptation to Life. Boston: Little, Brown.',
  lazarusFolkman1984: 'Lazarus, R. S. & Folkman, S. (1984). Stress, Appraisal, and Coping. New York: Springer.',
  bronfenbrenner1979: 'Bronfenbrenner, U. (1979). The Ecology of Human Development. Cambridge, MA: Harvard University Press.',
  bandura1977: 'Bandura, A. (1977). Self-efficacy: Toward a unifying theory of behavioral change. Psychological Review, 84(2), 191–215.',
  skinner1953: 'Skinner, B. F. (1953). Science and Human Behavior. New York: Macmillan.',
  siegel1999: 'Siegel, D. J. (1999). The Developing Mind. New York: Guilford.',
  vanDerKolk2014: 'van der Kolk, B. (2014). The Body Keeps the Score. New York: Viking.',
  perry2006: 'Perry, B. D. & Szalavitz, M. (2006). The Boy Who Was Raised as a Dog. New York: Basic Books.',
  joiner2005: 'Joiner, T. (2005). Why People Die by Suicide. Cambridge, MA: Harvard University Press.',
  figley1995: 'Figley, C. R. (Ed.) (1995). Compassion Fatigue. New York: Brunner/Mazel.',
  rogers1951: 'Rogers, C. R. (1951). Client-Centered Therapy. Boston: Houghton Mifflin.',
  deShazer1985: 'de Shazer, S. (1985). Keys to Solution in Brief Therapy. New York: Norton.',
  millerRollnick2013: 'Miller, W. R. & Rollnick, S. (2013). Motivational Interviewing (3rd ed.). New York: Guilford.',
  omer2004: 'Omer, H. & von Schlippe, A. (2004). Autorität durch Beziehung. Göttingen: Vandenhoeck & Ruprecht.',
  kazdin2008: 'Kazdin, A. E. (2008). The Kazdin Method for Parenting the Defiant Child. Boston: Houghton Mifflin.',
  crone2010: 'Crone, D. A., Hawken, L. S. & Horner, R. H. (2010). Responding to Problem Behavior in Schools: The Behavior Education Program (2nd ed.). New York: Guilford.',
  nolting2002: 'Nolting, H.-P. (2002). Störungen in der Schulklasse. Weinheim: Beltz.',
  wood1996: 'Wood, M. M. (1996). Developmental Therapy – Developmental Teaching (3rd ed.). Austin: Pro-Ed.',
  bergsson1998: 'Bergsson, M. & Luckfiel, H. (1998). Umgang mit „schwierigen“ Kindern. Berlin: Cornelsen Scriptor.',
  webbStratton2003: 'Webster-Stratton, C. & Reid, M. J. (2003). Treating conduct problems and strengthening social and emotional competence in young children: The Dina Dinosaur treatment program. Journal of Emotional and Behavioral Disorders, 11(3), 130–143.',
  doepfner2019: 'Döpfner, M., Schürmann, S. & Frölich, J. (2019). Therapieprogramm für Kinder mit hyperkinetischem und oppositionellem Problemverhalten THOP (6. Aufl.). Weinheim: Beltz.',
  petermann2012: 'Petermann, F. & Petermann, U. (2012). Training mit aggressiven Kindern (13. Aufl.). Weinheim: Beltz.',
  kendallHedtke2006: 'Kendall, P. C. & Hedtke, K. A. (2006). Cognitive-Behavioral Therapy for Anxious Children: Therapist Manual (3rd ed.). Ardmore, PA: Workbook Publishing.',
  gray2015: 'Gray, C. (2015). The New Social Story Book. Arlington, TX: Future Horizons.',
  mesibov2004: 'Mesibov, G. B., Shea, V. & Schopler, E. (2004). The TEACCH Approach to Autism Spectrum Disorders. New York: Springer.'
};
